name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        node-version: 21.x

    - name: Setup Pages
      uses: actions/configure-pages@v3

    - name: Install
      run: npm install

    - name: Type check
      run: npm run type

    - name: Lint
      run: npm run lint

    - name: Build
      run: npm run build

    - name: Upload
      uses: actions/upload-pages-artifact@v2
      with:
        path: './dist'

    - name: Deploy
      id: deployment
      uses: actions/deploy-pages@v2
